# Importing necessary libraries

In [2]:
import numpy as np
import pandas as pd
import joblib
from xgboost import XGBClassifier
from sklearn.datasets import load_breast_cancer

# Loading & preparing data for modeling

In [3]:
data = load_breast_cancer(as_frame= True)

In [4]:
data.data

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [5]:
data.data.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'],
      dtype='str')

In [6]:
features = ["mean radius", "mean texture", "mean perimeter", "mean area", "mean smoothness", "mean compactness", "mean concavity"]
X = data.data[features]
y = data.target

In [7]:
y_frame = pd.DataFrame({"target" :y})

In [8]:
y_frame.value_counts(normalize = True)

target
1         0.627417
0         0.372583
Name: proportion, dtype: float64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

# Modeling

In [11]:
# Let's perform cross-valiation
from sklearn.model_selection import KFold,cross_val_score

kf = KFold(n_splits = 5, shuffle = True, random_state = 42,)

model = XGBClassifier(n_jobs = -1)

cv_score = cross_val_score(model, X_train, y_train,cv = kf, scoring = "f1")

In [12]:
print(f"Le f1 score moyen de la validation croisée est: {np.mean(cv_score):.2f}")

Le f1 score moyen de la validation croisée est: 0.96

In [13]:
cv_score

array([0.96428571, 0.96551724, 0.96153846, 0.95      , 0.95798319])

In [14]:
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=-1, num_parallel_tree=None, ...)

In [15]:
test_pred= model.predict(X_test)

In [16]:
test_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [17]:
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report

cm = classification_report(y_test, test_pred)

In [18]:
print(cm)

              precision    recall  f1-score   support

           0       0.95      0.98      0.97        43
           1       0.99      0.97      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

In [19]:
f1 = f1_score(y_test, test_pred)

In [20]:
f1

0.9787234042553191

In [21]:
# confusion matrix

from sklearn.metrics import confusion_matrix

conf_m = confusion_matrix(y_test, test_pred)

In [22]:
conf_m

array([[42,  1],
       [ 2, 69]])

# Hyperparameter Tuning

In [23]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from scipy.stats import randint, uniform

In [24]:
# RDMS CV
pipeline = Pipeline([
    ("scaler",StandardScaler()),
    ("model", XGBClassifier(random_state= 42))
])

param_dist = {
    "model__n_estimators": randint(50, 200),
    "model__max_depth": randint(3, 10),
    "model__learning_rate": uniform(0.01, 0.3)
}

search = RandomizedSearchCV(
    pipeline,
    param_distributions = param_dist,
    n_iter = 15,
    cv = 5,
    scoring = "f1",
    random_state = 42,
    n_jobs = -1,
    verbose=True
)

print("="*15+"Début de la recherche aléatoire"+"="*15)
search.fit(X_train,y_train)

===============Début de la recherche aléatoire===============
Fitting 5 folds for each of 15 candidates, totalling 75 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                             ('model',
                                              XGBClassifier(base_score=None,
                                                            booster=None,
                                                            callbacks=None,
                                                            colsample_bylevel=None,
                                                            colsample_bynode=None,
                                                            colsample_bytree=None,
                                                            device=None,
                                                            early_stopping_rounds=None,
                                                            enable_categorical=True,
                                                            eval_metric=None,
                                                            feature_types=None,
                                                            feature_weights=None,
                                                            gamma=None,
                                                            grow_po...
                   param_distributions={'model__learning_rate': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x1121042f0>,
                                        'model__max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x11204df90>,
                                        'model__n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x1121041a0>},
                   random_state=42, scoring='f1', verbose=True)

In [25]:
print(f"Le meilleur f1-score est: {search.best_score_}")

Le meilleur f1-score est: 0.9565994932936462

In [26]:
print(f"Les meilleurs paramètres sont: {search.best_params_}")

Les meilleurs paramètres sont: {'model__learning_rate': np.float64(0.22959818254342154), 'model__max_depth': 7, 'model__n_estimators': 70}

In [27]:
# Pipeline serialisation
best_pipeline = search.best_estimator_

In [28]:
best_pipeline

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=True, eval_metric=None,
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None,
                               learning_rate=np.float64(0.22959818254342154),
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=7, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=70, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [29]:
import numpy; print(numpy.__version__)

2.5.3

In [30]:
joblib.dump(best_pipeline, "best_pipeline.pkl")

['best_pipeline.pkl']

In [31]:
X.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity'],
      dtype='str')

In [32]:
X.describe()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800